import { FadeIn, ToolFAQ } from "@/app/tools/_shared/components"
import { EmailROICalculator } from "./_components/EmailROICalculator"
import { EmailROIHowToUse } from "./_components/EmailROIHowToUse"
import { EmailROIGuide } from "./_components/EmailROIGuide"
import { CTA } from "@/components/sections/CTA"
import { Metadata } from "next"

export const metadata: Metadata = {
    title: "Email Marketing ROI Calculator | Free Tools",
    description: "Calculate the ROI of your email marketing campaigns. Optimize your open rates, click-through rates, and conversion rates to maximize profit.",
}

export default function EmailROICalculatorPage() {
    return (
        <div className="min-h-screen bg-slate-50 pt-32 pb-12">
            <div className="container mx-auto px-4">
                <div className="text-center mb-12">
                    <FadeIn>
                        <h1 className="text-4xl md:text-5xl font-bold text-slate-900 mb-4 tracking-tight">
                            Email Marketing ROI Calculator
                        </h1>
                    </FadeIn>
                </div>

                <div className="mb-20">
                    <EmailROICalculator />
                </div>

                <div className="max-w-4xl mx-auto space-y-16">
                    <FadeIn delay={0.2}>
                        <EmailROIHowToUse />
                    </FadeIn>

                    <FadeIn delay={0.3}>
                        <EmailROIGuide />
                    </FadeIn>

                    <FadeIn delay={0.4}>
                        <ToolFAQ
                            faqs={[
                                {
                                    question: "How is 'Total Revenue' calculated?",
                                    answer: "It is the simple product of your estimated <strong>Conversions</strong> (Sales) multiplied by your **Average Order Value (AOV)**. This represents the gross sales generated by the campaign before any costs are subtracted."
                                },
                                {
                                    question: "Why does my 'Subscriber Funnel' show 0 conversions?",
                                    answer: "If your list size or conversion rate is very small (e.g., 100 subscribers with a 1% conversion rate), the mathematical result might be less than 1 conversion (0.01). The tool rounds to the nearest whole number, showing 0 sales. Try increasing your list size to see projected results."
                                },
                                {
                                    question: "What is a 'good' Click-Through Rate (CTR)?",
                                    answer: "Across most industries, a <strong>2–5% CTR</strong> is considered average. Anything above 5% indicates highly relevant content or a very engaged list. If you are below 1%, consider testing new subject lines or clearer calls-to-action (CTAs)."
                                },
                                {
                                    question: "Should I include my own time in 'Campaign Cost'?",
                                    answer: "Yes! For an accurate ROI, you should assign a dollar value to the hours you spent writing, designing, and setting up the campaign. This helps you understand if your time is being invested profitably."
                                }
                            ]}
                        />
                    </FadeIn>

                    <FadeIn delay={0.5}>
                        <CTA withSectionWrapper={false} />
                    </FadeIn>
                </div>
            </div>
        </div>
    )
}
