"use client"
import { ToolSteps } from "@/app/tools/_shared/components"
import { CircleDollarSign, TrendingUp, BarChart3 } from "lucide-react"
export function ROIHowToUse() {
    return (
        <ToolSteps
            steps={[
                {
                    title: "Initial Cash",
                    description: "Enter strict overall total monetary capital permanently committed toward establishing the targeted core venture.",
                    icon: CircleDollarSign
                },
                {
                    title: "Final Return",
                    description: "Input precise explicit cash extracted currently generated by liquidating or completely finishing the base investment.",
                    icon: TrendingUp
                },
                {
                    title: "Check Value",
                    description: "Instantly discover sheer total percentage-driven metrics confirming absolute true financial return bounds and growth.",
                    icon: BarChart3
                }
            ]}
        />
    )
}