import { FadeIn, ToolFAQ, ToolPageTitle, ToolSectionHeader } from "@/app/tools/_shared/components"
import { DaysOfInventoryCalculator } from "./_components/DaysOfInventoryCalculator"
import { DaysOfInventoryHowToUse } from "./_components/DaysOfInventoryHowToUse"
import { DaysOfInventoryGuide } from "./_components/DaysOfInventoryGuide"
import { DaysOfInventoryOverview } from "./_components/DaysOfInventoryOverview"
import { CTA } from "@/components/sections/CTA"
import { Lightbulb } from "lucide-react"
import { Metadata } from "next"
export const metadata: Metadata = {
    title: "Days of Inventory Calculator | Stock Runway Forecast Tool",
    description: "Calculate how many days of inventory you have left based on current stock and sales velocity. Forecast your stock-out date and plan your next restock efficiently.",
}
export default function DaysOfInventoryCalculatorPage() {
    return (
        <div className="min-h-screen bg-slate-50 pt-32 pb-12">
            <div className="container mx-auto px-4">
                <ToolPageTitle title="Days of Inventory Remaining Calculator" />
                <div className="mb-20">
                    <DaysOfInventoryCalculator />
                </div>
                <div className="max-w-4xl mx-auto space-y-16">
                    <FadeIn delay={0.1}>
                        <ToolSectionHeader 
                            title="Tool Essential"
                            icon={Lightbulb}
                        />
                        <DaysOfInventoryOverview />
                    </FadeIn>
                    <FadeIn delay={0.2}>
                        <DaysOfInventoryHowToUse />
                    </FadeIn>
                    <FadeIn delay={0.3}>
                        <DaysOfInventoryGuide />
                    </FadeIn>
                    <FadeIn delay={0.4}>
                        <ToolFAQ
                            faqs={[
                                {
                                    question: "Should I select Daily, Weekly, or Monthly for my sales tracking?",
                                    answer: "Use the timeframe that you are most comfortable with! However, looking at 'Daily' velocity usually gives the most accurate runway calculations because it captures sudden day-to-day demand swings the best."
                                },
                                {
                                    question: "Should I include products currently being shipped to me?",
                                    answer: "No, this calculator looks exclusively at your physical on-hand stock right now. Simply compare your incoming shipment dates against the 'Expected Stock-Out Date' generated by this tool! If they arrive before the stock-out date, you are safe."
                                },
                                {
                                    question: "What dictates a good 'Safety Buffer'?",
                                    answer: "A Safety Buffer acts as an emergency parachute for unexpected delays or sudden sales surges. A good rule of thumb is keeping a few emergency days of stock tucked away on the sidelines at all times to avoid frustrated customers."
                                },
                                {
                                    question: "What is 'Actionable Stock Runway' and why does it matter?",
                                    answer: "Your Actionable Stock Runway shows exactly how many days of inventory you have left before dipping into your emergency Safety Buffer. This is your safe timeline—you generally should reorder before this hits zero!"
                                },
                                {
                                    question: "What do the status indicators (Critical, Warning, Healthy, Overstock) mean?",
                                    answer: "CRITICAL: Less than 7 days left—reorder right away! WARNING: 7-21 days left. HEALTHY: 21-90 days left—the inventory 'sweet spot'. OVERSTOCK: Over 90 days of inventory—be careful of tying up too much cash in products just sitting on shelves."
                                }
                            ]}
                        />
                    </FadeIn>
                    <FadeIn delay={0.5}>
                        <CTA withSectionWrapper={false} />
                    </FadeIn>
                </div>
            </div>
        </div>
    )
}
