"use client"
import { ToolSteps } from "@/app/tools/_shared/components"
import { Wallet, DollarSign, TrendingUp } from "lucide-react"

export function InfluencerHowToUse() {
    return (
        <ToolSteps
            title="How to Calculate Campaign Success"
            steps={[
                {
                    title: "Enter Campaign Cost",
                    description: "Input your total money spent on the partnership. For a deeper analysis, click <strong>Add Details</strong> to break costs down into Influencer Fees, Ad Spend, Product Costs, and Shipping.",
                    icon: Wallet
                },
                {
                    title: "Add Your Revenue",
                    description: "Enter the total sales amount generated by the influencer's promotion or promo code.",
                    icon: DollarSign
                },
                {
                    title: "See Your True Return",
                    description: "Instantly view your net <strong>Profit/Loss</strong> and total <strong>ROI percentage</strong> to determine if the campaign was a financial success.",
                    icon: TrendingUp
                }
            ]}
        />
    )
}
