import { Metadata } from "next";
import { TACoSCalculator } from "./_components/TACoSCalculator";
import { TACoSHowToUse } from "./_components/TACoSHowToUse";
import { TACoSGuide } from "./_components/TACoSGuide";
import { TACoSOverview } from "./_components/TACoSOverview";
import { FadeIn, ToolFAQ, ToolPageTitle } from "@/app/tools/_shared/components";
import { CTA } from "@/components/sections/CTA";
export const metadata: Metadata = {
    title: "Total Advertising Cost of Sales (TACoS) Calculator",
    description: "Calculate your Total Advertising Cost of Sales (TACoS) to measure the long-term health of your e-commerce brand.",
};
export default function TACoSPage() {
    return (
        <div className="min-h-screen bg-slate-50 pt-32 pb-12">
            <div className="container mx-auto px-4">
                <ToolPageTitle 
                    title="Total Advertising Cost of Sales Calculator"
                    direction="down"
                    duration={0.6}
                />
                <TACoSCalculator />
                <div className="max-w-4xl mx-auto mt-20 space-y-16">
                    <FadeIn delay={0.1}>
                        <TACoSOverview />
                    </FadeIn>
                    <div id="how-to-use">
                        <FadeIn delay={0.1}>
                            <TACoSHowToUse />
                        </FadeIn>
                    </div>
                    <FadeIn delay={0.2}>
                        <TACoSGuide />
                    </FadeIn>
                    <FadeIn delay={0.2}>
                        <ToolFAQ
                            faqs={[
                                {
                                    question: "What exactly is Total Advertising Cost of Sales (TACoS)?",
                                    answer: "TACoS measures the relationship between your total ad spend and your total overall revenue (both organic and paid). It tracks your brand's ad-dependency and overall profitability."
                                },
                                {
                                    question: "What is considered a 'good' TACoS?",
                                    answer: "Healthy TACoS depends heavily on your business stage. For established brands, <strong>10-15%</strong> is often considered a healthy baseline. For aggressive new product launches, it might temporarily spike to <strong>20-30%</strong> as you heavily invest in gaining market share."
                                },
                                {
                                    question: "How does TACoS differ from ACoS?",
                                    answer: "ACoS only measures the efficiency of your paid ad campaigns (Ad Spend ÷ Ad Revenue). TACoS measures the health of your entire business (Ad Spend ÷ Total Revenue) and accounts for the organic sales generated by increased brand visibility."
                                },
                                {
                                    question: "Why is my TACoS rapidly rising?",
                                    answer: "A rising TACoS means your ad investments are growing faster than your overall revenue. This typically points to ads becoming more expensive or less effective, or a sudden drop in your organic search traffic and sales."
                                },
                                {
                                    question: "How frequently should I check my TACoS?",
                                    answer: "Weekly and monthly monitoring is best to establish a trendline. Daily fluctuations are completely normal in retail and usually do not reflect the true long-term impact of your advertising strategy."
                                }
                            ]}
                        />
                    </FadeIn>
                    <FadeIn delay={0.2}>
                        <CTA />
                    </FadeIn>
                </div>
            </div>
        </div>
    );
}